<p style='margin:0in;text-align:center;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-size:16px;">CONTRATO DE ARRENDAMIENTO</span></p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">En la ciudad de Tijuana, Baja California, se re&uacute;nen por parte el (la) se&ntilde;or (a)</span> <u>Sonia Renter&iacute; Gonzalez</u> <span style="font-weight:normal;">&nbsp;y por otra parte el (la) se&ntilde;or (a</span>) <u><?php echo ucfirst($response['data']['ename']); ?></u> <span style="font-weight:normal;">a los cuales se les denominar&aacute; para los fines del presente contrato como&nbsp;</span>&ldquo;ARRENDADOR&rdquo;<span style="font-weight:normal;">&nbsp;y&nbsp;</span>&ldquo;ARRENDATARIO&rdquo;<span style="font-weight:normal;">&nbsp;respectivamente, conviniendo ambos en sujetarse a las siguientes declaraciones y cl&aacute;usulas:</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:center;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>DECLARACIONES</p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<div style='margin:0in;font-size:16px;font-family:"Times New Roman",serif;'>
    <ol style="margin-bottom:0in;list-style-type: decimal;margin-left:0in;">
        <li style='margin:0in;font-size:16px;font-family:"Times New Roman",serif;'>Declara el&nbsp;&ldquo;ARRENDADOR&rdquo;&nbsp;que es el leg&iacute;timo due&ntilde;o del inmueble ubicado en:</li>
    </ol>
</div>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;margin-left:.25in;text-indent:17.4pt;'>Calle Ladera No. 7 Int. 1 Col. Ju&aacute;rez.</p>
<ol style="list-style-type: undefined;margin-left:0in;">
    <li>Declara el&nbsp;&ldquo;ARRENDATARIO&rdquo;&nbsp;que es su libre voluntad tomar el arrendamiento del bien inmueble se&ntilde;alado en la primera declaraci&oacute;n.</li>
    <li>Declara el&nbsp;&ldquo;ARRENDATARIO&rdquo;&nbsp;que conoce perfectamente le bien inmueble materia del presente contrato, por lo que no tiene ning&uacute;n inconveniente en rentarlo al&nbsp;&ldquo;ARRENDADOR&rdquo;.</li>
</ol>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:center;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>CLAUSULAS</p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:left;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>PRIMERA.- &nbsp;<span style="font-weight:normal;">El precio mensual del arrendamiento ser&aacute; la cantidad de $<?php echo $response['data']['total']; ?> <?php echo $response['data']['currency']; ?></span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>;&nbsp;<span style="font-weight:normal;">pagadera en mensualidades adelantadas al &ldquo;ARRENDADOR&rdquo; , o a quien en sus derechos represente en sus oficinas ubicadas en&nbsp;</span>Calle Mizar No. 21 Col. Postal.</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>SEGUNDA.- &nbsp;<span style="font-weight:normal;">El &ldquo;ARRENDATARIO&rdquo; pagar&aacute; una pena convencional del </span><?php echo $response['data']['interestrate']*100; ?>%<span style="font-weight:normal;">&nbsp;del importe de la renta si no la cubriera dentro de los <?php echo $response['data']['daysoftolerance']; ?> primeros d&iacute;as de aquel en que se haga exigible la misma.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>TERCERA.- &nbsp;<span style="font-weight:normal;">El t&eacute;rmino del presente contrato que empieza a correr con fecha del&nbsp;</span><?php echo $response['data']['startdate']; ?> al <?php echo $response['data']['enddate']; ?>.</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>CUARTA.- &nbsp;<span style="font-weight:normal;">La casa rentada se destinar&aacute; exclusivamente para&nbsp;</span> <u><?php echo $response['data']['type']; ?></u> <span style="font-weight:normal;">y si se hiciera otro uso de ella ser&aacute; motivo suficiente para que el &ldquo;ARRENDADOR&rdquo; pida la rescisi&oacute;n del presente contrato.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>QUINTA.- &nbsp;<span style="font-weight:normal;">El &ldquo;ARRENDATARIO&rdquo; no podr&aacute; subarrendar el inmueble material del presente contrato, ni traspasar sus derechos de arrendatario salvo que cuente con el permiso dado por escrito del &ldquo;ARRENDADOR, renunciando el primero al derecho que le concede el art&iacute;culo 2357 del C&oacute;digo civil vigente del Estado.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>SEXTA.- &nbsp;<span style="font-weight:normal;">Este contrato de arrendamiento termina por las diversas causas fijadas en el art&iacute;culo 2357 del C&oacute;digo Civil y adem&aacute;s por el cumplimiento del t&eacute;rmino fijado por el vencido dicho t&eacute;rmino; el &ldquo;ARRENDATARIO&rdquo; desocupara el inmueble y lo devolver&aacute; al &ldquo;ARRENDADOR&rdquo; o a quien en sus derechos represente; pues se conviene que este contrato no es prorrogable y por lo mismo, renuncia a los derechos que le conceden los art&iacute;culos 2359 y 2360 del C&oacute;digo Civil.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>S&Eacute;PTIMA.- &nbsp;<span style="font-weight:normal;">El &ldquo;ARRENDATARIO&rdquo; se compromete a pagar por su cuenta todos los servicios propios del inmueble arrendado, tales como&nbsp;</span>agua, luz, tel&eacute;fono, etc;&nbsp;<span style="font-weight:normal;">as&iacute; mismo se compromete a exhibir los recibos correspondientes; y pagados &nbsp;al &ldquo;ARRENDADOR&rdquo; en forma bimestral.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>OCTAVA.- &nbsp;<span style="font-weight:normal;">El &ldquo;ARRENDATARIO&rdquo; no podr&aacute; variar la forma de la casa arrendada, ni hacer mejoras &uacute;tiles no ornato sobre la misma, si no con el consentimiento dado por escrito por el &ldquo;ARRENDADOR&rdquo;.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>NOVENA.- &nbsp;<span style="font-weight:normal;">El &ldquo;ARRENDATARIO&rdquo; ser&aacute; responsable de los da&ntilde;os que sufra el inmueble material del presente contrato cualquier que fuera su causa; ya ser que lo realicen sus familiares, dependientes, empleados, etc.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>DECIMA.- &nbsp;<span style="font-weight:normal;">Para garantizar el cumplimiento de este contrato se obliga como&nbsp;</span>&ldquo;FIADOR SOLIDARIO&rdquo;&nbsp;<span style="font-weight:normal;">el se&ntilde;or (a) </span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">Con domicilio en:&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">quien renuncia a los beneficios de orden y exclusi&oacute;n contemplados en los art&iacute;culos 2684 y 2687 del C&oacute;digo Civil vigente en el Estado. La responsabilidad del &ldquo;FIADOR SOLIDARIO&rdquo; no cesar&aacute; hasta que el &ldquo;ARRENDADOR&rdquo; reciba la propiedad arrendada y que haya cumplido todas las obligaciones por parte del &ldquo;ARRENDATARIO&rdquo; y que constan en el presente contrato fuere prorrogado, la responsabilidad del &ldquo;FIADOR&rdquo; subsistir&aacute; y por lo mismo renuncia a los derechos que les concede el art&iacute;culo 2362 del C&oacute;digo Civil.</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Times New Roman",serif;text-align:justify;'><strong><span style='font-size:13px;font-family:"Tahoma",sans-serif;color:black;'>DECIMA PRIMERA.- &nbsp;</span></strong><span style='font-size:13px;font-family:"Tahoma",sans-serif;color:black;'>El &ldquo;ARRENDATARIO&rdquo; para garantizar da&ntilde;os que se puedan ocasionar en el bien arrendado o el pago de los servicios propios del mismo; entrega dos meses de renta como dep&oacute;sito por la &nbsp;cantidad de:&nbsp;</span><span style='font-size:13px;font-family:"Tahoma",sans-serif;'>mismos que en ning&uacute;n momento podr&aacute;n ser utilizados para el pago de los &uacute;ltimos meses de renta y en caso de incumplimiento del plazo del presente contrato, el dep&oacute;sito no ser&aacute; devolutivo.<strong>&nbsp;<span style="color:black;">&nbsp;</span></strong></span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'><span style="font-weight:normal;">&nbsp;</span></p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>Tijuana, B.C a., 27 de Octubre del 2022.</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&ldquo;EL ARRENDADOR&rdquo; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&ldquo;EL ARRENDATARIO&rdquo;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp; &nbsp;&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&ldquo;TESTIGO&rdquo; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &ldquo;TESTIGO&rdquo;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;text-indent:35.4pt;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;text-indent:35.4pt;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;text-indent:35.4pt;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;text-indent:35.4pt;'>&nbsp;</p>
<p style='margin:0in;text-align:justify;font-size:13px;font-family:"Tahoma",sans-serif;font-weight:bold;'>&nbsp;&nbsp;</p>
<p style='margin:0in;font-size:16px;font-family:"Times New Roman",serif;'>&nbsp;</p>